version: '3.3'
services:
  magento2-php:
    container_name: magento2-php
    image: magento2php:latest
    networks:
      - magento2
    volumes:
      - ./magento2:/var/www/magento2:cached
    depends_on:
      - magento2-mysql
      - magento2-elasticsearch

  magento2-cron:
    container_name: magento2-cron
    image: magento2php:latest
    networks:
      - magento2
    volumes:
      - ./magento2:/var/www/magento2:cached
      - ./crontabs:/var/spool/cron/crontabs:cached
    depends_on:
      - magento2-php
    command: bash -c "cron && sleep 60s && tail -F /var/www/magento2/var/log/*cron.log"

  magento2-nginx:
    container_name: magento2-nginx
    build: ./nginx/
    image: magento2-nginx:latest
    networks:
      - magento2
    ports:
      - 8081:80
    volumes:
      - ./magento2:/var/www/magento2:ro,cached
    depends_on:
      - magento2-php

  magento2-mysql:
    container_name: magento2-mysql
    image: mysql:8.0
    networks:
      - magento2
    environment:
      MYSQL_ROOT_PASSWORD: r00t_p@ssw0rd
      MYSQL_USER: magento2
      MYSQL_PASSWORD: m@gent02_p@ssW0rd
      MYSQL_DATABASE: magento2
    volumes:
      - ./db-data:/var/lib/mysql
    restart: on-failure
  
  magento2-elasticsearch:
    container_name: magento2-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    networks:
      - magento2
    environment:
      discovery.type: single-node
      ports:
        9200:9200
        9300:9300
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    restart: on-failure

networks:
  magento2:
    external: true
